### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yangyl7239** [harvard-acc/gem5-aladdin#32] opened 2020-10-28 08:25 UTC
root@5e60d163e16d:/workspace/gem5-aladdin/sweeps# python generate_design_sweeps.py benchmarks/machsuite.xe
use benchmarks.designsweeptypes.Gem5DesignSweep
begin Gem5DesignSweep single
use benchmarks.machsuite.*
generate configs
generate dma_trace
generate gem5_binary
set output_dir "machsuite"
set source_dir "../src/aladdin/MachSuite"
set simulator "gem5-cpu"
set memory_type "spad"
sweep cycle_time from 1 to 5
set unrolling for bfs_bulk.bfs.loop_horizons 1
On line 4: set unrolling for bfs_bulk.bfs.loop_horizons 1
XenonSelectionError: Failed to find object named b.f.s._.b.u.l.k
root@5e60d163e16d:/workspace/gem5-aladdin/sweeps#

**Comment by xyzsam** [comment] 2020-11-08 05:54
Duplicate of https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gem5-aladdin-users/8eL3zOQj7GE/lxhX3mCNAAAJ.

**Closed by xyzsam** 2020-11-08 05:54 UTC

**Comment by mjtsai** [comment] 2021-12-15 13:14
I'm newbie to use gem5 and this issue also occurs in my environment.
I'm not sure it's the correct solution but removing the indexed symbol makes it work.

diff --git a/base/common.py b/base/common.py
index 991253c..efdf255 100644
--- a/base/common.py
+++ b/base/common.py
@@ -28,7 +28,7 @@ def getSelectedObjs(select_tokens, env):
     select_tokens.append(LIT_STAR)
 
   current_view = env
-  for token in select_tokens[0]:
+  for token in select_tokens:
     if token == LIT_STAR:
       break
     try:

**Comment by xyzsam** [comment] 2021-12-20 14:50
Do you have the `end <sweep_name>` statement at the end?

**Comment by mjtsai** [comment] 2021-12-21 13:54
> Do you have the `end <sweep_name>` statement at the end?

yes, I ran the example, machsuite.xe.
